<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function adyax_test_ctools_plugin_api($owner, $api) {
  if ($owner == 'panels') {
    return array('version' => 2.0);
  }
}

/**
 * Implemets hook_ctools_plugin_directory().
 */
function adyax_test_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && in_array($plugin, array('content_types'))) {
    return 'plugins/' . $plugin;
  }
}

function adyax_test_preprocess_adyax_test_adyaxtheme(&$vars) {
  if (is_numeric($vars['border_width'])) {
    $vars['attributes_array'] = array(
      'style' => 'border: ' . $vars['border_width'] . 'px solid gray!important; border-radius: 10px!important;',
    );
  }
}