<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function adyax_test_ctools_plugin_api($owner, $api) {
  if ($owner == 'panels') {
    return array('version' => 2.0);
  }
}

/**
 * Implemets hook_ctools_plugin_directory().
 */
function adyax_test_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && in_array($plugin, array('content_types'))) {
    return 'plugins/' . $plugin;
  }
  if ($module == 'panels' && in_array($plugin, array('styles'))) {
    return 'plugins/' . $plugin;
  }
}